In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("PeoplesFavourites-1.csv")

In [3]:
df.sample(25)

,Job Title,Interests,Interests.1,Education Level,City,Food,Food.1,Car,Income,Movie,Movie.1,First Name,Last Name,Email
805,Systems Administrator,Music,NaN,Junior college,Omaha,Taco Bell,none,Fiat Freemont,620838,History,NaN,Madison,Squire,Madison_Squire9418@acrit.org
24,Laboratory Technician,Instrumental Music,Accounting,High school,Bridgeport,Knorr,Vitta Foods,Citroen C4,101958,Thriller,Adventure,Noah,Andrews,Noah_Andrews9063@joiniaa.com
914,Laboratory Technician,French,American Literature,University-preparatory school,Jacksonville,M&M Food Market,Tic Tac,Mitsubishi Lancer,559042,Comedy,Biography,Phillip,Vincent,Phillip_Vincent6864@bungar.biz
877,Cook,Instrumental Music,Earth Science,Technical college,Wien,KFC,Secret Recipe,Fiat Panda,96973,Adventure,Biography,Phillip,Ulyatt,Phillip_Ulyatt2411@nanoff.biz
588,Front Desk Coordinator,Art,Economics,High school,Rochester,Andy Capp's fries,Starbucks,Ford Focus,491837,Animation,Fantasy,Boris,Oliver,Boris_Oliver568@eirey.tech
77,Design Engineer,Science,Geography,Technical college,Nashville,Subway,Carib Brewery,Audi Q6,192651,Sci-Fi,Family,Jocelyn,Bloom,Jocelyn_Bloom3242@nimogy.biz
830,Auditor,Dramatics,Economics,Middle school,Murfreesboro,Applebee's,Vitta Foods,Audi V8,217250,Romance,Crime,Destiny,Stuart,Destiny_Stuart8717@zorer.org
866,Systems Administrator,Dramatics,Music,High school,Memphis,Nutella,Applebee's,Hyundai i20,338405,Musical,Thriller,Martin,Trent,Martin_Trent9001@grannar.com
415,HR Coordinator,Earth Science,NaN,Graduate school,Hollywood,Papadopoulos,none,Mitsubishi Lancer,742250,Thriller,NaN,Teagan,Jeffery,Teagan_Jeffery2392@cispeto.com
596,Inspector,Physical Education,English IV,Public university,Bridgeport,Wendy's,KFC,Honda Civic,377300,History,Drama,Leroy,Owen,Leroy_Owen2756@guentu.biz
732,Web Developer,Health,Music,Graduate school,Salt Lake City,McDonald's,Dunkin' Donuts,Fiat Panda,678505,Drama,Animation,Catherine,Rose,Catherine_Rose5718@yahoo.com
1011,Business Broker,Science,Economics,High school,Long Beach,LEonidas,Wonder Bread,Hyundai i35,500059,Comedy,Romance,Jacob,NaN,Jacob_Bolton6977@jiman.org
884,Designer,Spanish,Geography,Public university,Memphis,Kinder,Starbucks,Citroen C3,731150,Action,Horror,Maya,Upsdell,Maya_Upsdell5252@typill.biz
391,HR Specialist,Sociology,Accounting,Middle school,Cincinnati,KFC,Nutella,Citroen Jumper,331179,Thriller,Comedy,Phillip,Isaac,Phillip_Isaac7160@guentu.biz
112,Cashier,Design and technology,Health,Gymnasium,Hayward,Bel Group,Pizza Hut,Hyundai Santa Fe,573828,History,Family,Logan,Butler,Logan_Butler4607@bauros.biz
346,Front Desk Coordinator,Music,Geography,Gymnasium,Innsbruck,Bel Group,Knorr,Audi V8,825372,Romance,Biography,Anthony,Harrison,Anthony_Harrison9589@ubusive.com
185,Auditor,French,Spanish,Middle school,Lancaster,Vitta Foods,Soprole,Audi Q3,613699,Romance,Horror,Maia,Davies,Maia_Davies3627@famism.biz
689,IT Support Staff,Handwriting,Dramatics,Corporate university,Glendale,Bewley's,Domino,Ford Mustang,349238,Fantasy,Adventure,Joyce,Reid,Joyce_Reid6316@brety.org
659,Project Manager,NaN,NaN,Corporate university,St. Louis,NaN,none,0,0,0,NaN,Marvin,Preston,Marvin_Preston3955@bretoux.com
262,Cashier,Economics,Resource Program,Middle school,Louisville,Soprole,Vitta Foods,Honda Civic,606176,History,Romance,Alan,Flanders,Alan_Flanders5834@nanoff.biz
646,Software Engineer,Earth Science,Language Arts,Gymnasium,Los Angeles,M&M Food Market,Taco Bell,Honda CRV,496891,Family,Adventure,Bob,Potter,Bob_Potter2434@cispeto.com
573,Bookkeeper,Resource Program,Speech,Junior college,Dallas,Lavazza,Wendy's,Citroen Nemo,725832,Romance,Drama,Moira,Norburn,Moira_Norburn8989@naiker.biz
723,Pharmacist,Earth Science,History,Graduate school,New Orleans,Magnum,Subway,Fiat Freemont,41056,Musical,Drama,Harry,Roscoe,Harry_Roscoe6855@muall.tech
202,HR Specialist,Basic Math,Mathematics,Corporate university,Baltimore,Heinz,Pizza Hut,Hyundai Santa Fe,372903,History,Family,Chad,Donovan,Chad_Donovan5533@atink.com
639,Paramedic,none,NaN,Gymnasium,Minneapolis,none,NaN,NaN,0,NaN,none,Abdul,Pond,none

#### Anonymize the data by removing the customer names (first and last name) replacing with a unique identifier.

In [4]:
# Anonymyze  First Name and Last Name by creating a unique Id and drop First Name and Last Name
df['Name_Id'] = (df['First Name'] + '_' + df['Last Name']).astype('category').cat.codes
df.drop(columns=['First Name','Last Name'], inplace=True)

In [5]:
# anonymyze the email address
df['Email'] = df['Name_Id'].map(str)+'@'+ df['Email'].str.extract("@(.*)")[0]

In [6]:
df.sample(25)

,Job Title,Interests,Interests.1,Education Level,City,Food,Food.1,Car,Income,Movie,Movie.1,Email,Name_Id
497,Baker,French,Art,Public university,Rochester,Applebee's,Magnum,Hyundai Santa Fe,494318,Comedy,Animation,346@bretoux.com,346
768,Software Engineer,none,NaN,Corporate university,Oklahoma City,none,NaN,Hyundai Santa Fe,219371,0,none,951@ubusive.com,951
787,Healthcare Specialist,Sociology,NaN,Junior college,Baltimore,LEonidas,NaN,Mitsubishi Lancer,699608,Horror,0,26@sveldo.biz,26
489,Insurance Broker,Geography,Earth Science,University college,Miami,Nutella,Burger King,BMW M5,884272,Crime,Biography,NaN,829
347,Designer,Handwriting,Physical Education,Public university,Lisbon,Lavazza,Cheetos,Hyundai i20,563256,Romance,Romance,946@deavo.com,946
659,Project Manager,NaN,NaN,Corporate university,St. Louis,NaN,none,0,0,0,NaN,652@bretoux.com,652
290,Food Technologist,German,French,University-preparatory school,Lincoln,Soprole,Cheetos,BMW X5,15321,Comedy,Romance,732@famism.biz,732
504,Steward,NaN,NaN,Public university,Orlando,NaN,NaN,NaN,0,0,NaN,825@supunk.biz,825
155,Steward,none,none,Gymnasium,Louisville,NaN,none,NaN,0,NaN,NaN,553@guentu.biz,553
635,Staffing Consultant,Trigonometry,Sociology,Public university,Lisbon,Soprole,Soprole,Citroen Jumper,702558,Adventure,History,778@vetan.org,778
854,Inspector,Mathematics,Accounting,Gymnasium,Scottsdale,Nutella,Bewley's,Mitsubishi Outlander,443525,Musical,Romance,885@zorer.org,885
972,Loan Officer,English IV,Mathematics,Technical college,Cincinnati,Applebee's,Kinder,Kia Sportage,472200,Thriller,Family,429@cispeto.com,429
334,Retail Trainee,Accounting,NaN,University-preparatory school,Scottsdale,KFC,none,Audi R8,601515,Crime,0,323@typill.biz,323
47,Business Broker,Ecology,Economics,University-preparatory school,Valetta,Carib Brewery,Knorr,BMW X5,894308,Crime,Family,592@guentu.biz,592
919,Insurance Broker,German,Dramatics,Public university,Hayward,KFC,Dunkin' Donuts,Fiat Panda,85305,Biography,Sci-Fi,874@irrepsy.com,874
877,Cook,Instrumental Music,Earth Science,Technical college,Wien,KFC,Secret Recipe,Fiat Panda,96973,Adventure,Biography,792@nanoff.biz,792
647,Business Broker,Accounting,Leadership,Technical college,Colorado Springs,Tic Tac,Bewley's,Citroen Nemo,664653,Romance,Fantasy,-1@liret.org,-1
700,Stockbroker,Economics,Instrumental Music,Corporate university,Ontario,Knorr,Lavazza,Kia Ceed,121546,Comedy,Thriller,479@gembat.biz,479
25,Staffing Consultant,Mathematics,English IV,Graduate school,San Antonio,Bel Group,Magnum,BMW X1,598358,Action,Thriller,966@qater.org,966
461,Executive Director,Leadership,LOGIC,Gymnasium,Paris,Nutella,Dr. Oetker,Honda Civic,356401,Adventure,Crime,863@nickia.com,863
193,Bellman,Art,Design and technology,University-preparatory school,Lakewood,Baskin robbins,Kits,Ford Focus,754530,Crime,Crime,612@fuliss.net,612
314,Doctor,American Literature,Earth Science,Middle school,Milano,Bewley's,Starbucks,Hyundai Tucson,41959,Adventure,Drama,715@vetan.org,715
410,Production Painter,Health,NaN,High school,Jacksonville,Bewley's,none,BMW M4,300416,Romance,NaN,177@liret.org,177
101,HR Specialist,Language Arts,Dramatics,Public university,Springfield,Betty Crocker,Heinz,Audi TT,780828,History,History,537@gembat.biz,537
74,Business Broker,NaN,none,University-preparatory school,Quebec,NaN,none,0,0,NaN,NaN,551@elnee.tech,551

#### A number of different symbols (including space) have been used for null values, select and apply a consist ant approach to their representation.

In [7]:
df = df.replace(['\b','0', 'none'], np.nan)
df = df.replace(0, -1)

In [8]:
df.sample(25)

,Job Title,Interests,Interests.1,Education Level,City,Food,Food.1,Car,Income,Movie,Movie.1,Email,Name_Id
370,Inspector,Art,Mathematics,Junior college,Quebec,Baskin robbins,Vitta Foods,Hyundai i20,447047,Family,Thriller,452@cispeto.com,452
717,Chef Manager,English IV,Design and technology,Corporate university,Bellevue,Baskin robbins,Andy Capp's fries,Kia Ceed,840952,Biography,Fantasy,148@acrit.org,148
856,HR Coordinator,English IV,Ancient Civilizations,Technical college,Chicago,Heinz,Heinz,Hyundai i30,340475,Family,History,309@ovock.tech,309
265,HR Coordinator,Instrumental Music,French,University-preparatory school,Murfreesboro,M&M Food Market,Papadopoulos,Citroen Jumper,205916,Drama,Musical,80@bungar.biz,80
524,Associate Professor,English IV,French,Graduate school,Prague,Wonder Bread,Secret Recipe,Mazda CX5,612719,Fantasy,Family,308@tonsy.org,308
589,Bookkeeper,Speech,Handwriting,Gymnasium,Berna,Secret Recipe,KFC,Fiat Cronos,753451,Family,Sci-Fi,424@iatim.tech,424
687,Budget Analyst,Geography,Trigonometry,Technical college,Wien,Papadopoulos,Baskin robbins,Fiat Panda,675917,Thriller,Drama,379@brety.org,379
961,Chef Manager,Mathematics,Design and technology,Corporate university,Chicago,Andy Capp's fries,McDonald's,Audi A4,368240,Family,Romance,470@bretoux.com,470
501,Software Engineer,German,Economics,Graduate school,Springfield,Carib Brewery,Bewley's,Audi Cabriolet,852550,Sci-Fi,Adventure,397@iatim.tech,397
285,Pharmacist,Resource Program,Science,Middle school,New York,Nabisco,Andy Capp's fries,Audi Q5,266081,Adventure,Animation,856@kideod.biz,856
116,Dentist,Grammar,English IV,Gymnasium,Santa Ana,Tic Tac,Domino,Hyundai i30,37755,Romance,Fantasy,899@muall.tech,899
179,Healthcare Specialist,Physical Education,German,Corporate university,Madrid,KFC,Doritos,Kia Soul,143876,Biography,Action,42@irrepsy.com,42
966,Web Developer,Grammar,Science,Public university,Lancaster,Knorr,Vitta Foods,Honda CRV,381030,History,Family,365@brety.org,365
763,Baker,Dramatics,Health,University-preparatory school,Reno,Domino,Papadopoulos,Audi A6,739157,Horror,Thriller,810@infotech44.tech,810
484,Webmaster,Art,Trigonometry,High school,Lancaster,Doritos,KFC,Mitsubishi Outlander,366146,Adventure,Thriller,459@joiniaa.com,459
682,Doctor,Resource Program,Trigonometry,Junior college,Sacramento,KFC,Magnum,Kia Sportage,842564,Animation,Animation,722@sheye.org,722
634,Inspector,Modern Literature,NaN,Graduate school,San Diego,Andy Capp's fries,NaN,BMW M4,501753,Drama,NaN,913@hourpy.biz,913
516,Call Center Representative,German,Art,Junior college,Fremont,Cobblestone,Doritos,Opel Insignia,337238,Family,Adventure,265@kideod.biz,265
429,Lecturer,French,Sociology,University-preparatory school,Bridgeport,Subway,Red Lobster,Fiat Panda,622400,History,Animation,512@sveldo.biz,512
654,Fabricator,Earth Science,Handwriting,Junior college,Tallahassee,Domino,Subway,Audi Q5,632305,Crime,Musical,954@liret.org,954
679,Cook,Design and technology,Design and technology,Public university,Nashville,Nabisco,Pizza Hut,BMW X5,542856,Romance,Comedy,296@womeona.net,296
861,Doctor,Grammar,Design and technology,Technical college,San Francisco,Pizza Hut,Heinz,Kia Soul,317021,Animation,Crime,744@sheye.org,744
244,Treasurer,Accounting,Art,Technical college,St. Louis,M&M Food Market,Starbucks,Mitsubishi Outlander,591978,Romance,Sci-Fi,203@bungar.biz,203
341,Health Educator,Language Arts,German,University-preparatory school,Hayward,Secret Recipe,LEonidas,Dacia Logan,335079,Sci-Fi,Drama,883@nickia.com,883
772,Clerk,Design and technology,Ancient Civilizations,Middle school,Murfreesboro,Starbucks,Burger King,Citroen C3,770683,Crime,Fantasy,38@iatim.tech,38

#### Remove any customer data that has missing data in any of the following first name, last name and email.

In [23]:
index = df[ (df['Email'].isnull()) | (df['Name_Id'] == -1)].index
df.drop(index , inplace=True)

In [25]:
df[df['Email'].isnull() | df['Name_Id'] == -1]

Empty DataFrame
Columns: [Job Title, Interests, Interests.1, Education Level , City, Food, Food.1, Car, Income, Movie, Movie.1, Email, Name_Id]
Index: []

#### export the data to a new file

In [26]:
df.to_csv('PeoplesFavourites-clean.csv')